# Generated by Django 3.2 on 2022-12-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('blog', models.TextField()),
                ('image', models.ImageField(upload_to='blogs_images/')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.TextField()),
                ('logo', models.ImageField(upload_to='company_images')),
                ('location', models.TextField()),
                ('contact', models.TextField()),
                ('email', models.TextField()),
                ('opening_hours', models.TextField()),
                ('no_of_clients', models.TextField()),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('about_us_page_heading_text', models.TextField()),
                ('about_us_page_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('subject', models.TextField()),
                ('contact', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.ImageField(upload_to='partner_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField()),
                ('image', models.ImageField(upload_to='slider_images')),
                ('text_1', models.TextField(blank=True, null=True)),
                ('text_2', models.TextField(blank=True, null=True)),
                ('text_3', models.TextField(blank=True, null=True)),
                ('button_text', models.TextField(blank=True, null=True)),
                ('custom_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('image', models.ImageField(upload_to='team_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField()),
                ('name', models.TextField()),
                ('company', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
