# Generated by Django 3.2 on 2022-12-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='partner_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
