# Generated by Django 3.2 on 2022-12-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(),
        ),
    ]
