# Generated by Django 3.2 on 2022-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_faqs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(upload_to='brochures')),
            ],
        ),
    ]
