# Generated by Django 3.2 on 2022-12-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_auto_20221229_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
    ]
