# Generated by Django 3.2 on 2022-12-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0009_auto_20221229_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.TextField()),
                ('image', models.ImageField(upload_to='team_images')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
