# Generated by Django 3.2 on 2022-12-30 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0013_borrower_shareholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '1. Slider'},
        ),
    ]
