# Generated by Django 3.2 on 2022-12-30 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('features', '0014_alter_slider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '12. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'verbose_name_plural': '05. Board Members'},
        ),
        migrations.AlterModelOptions(
            name='borrower',
            options={'verbose_name_plural': '11. Borrowers'},
        ),
        migrations.AlterModelOptions(
            name='brochures',
            options={'verbose_name_plural': '09. Brochures'},
        ),
        migrations.AlterModelOptions(
            name='companysetup',
            options={'verbose_name_plural': '01. Company Setup'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '13. Borrowers'},
        ),
        migrations.AlterModelOptions(
            name='faqs',
            options={'verbose_name_plural': '08. FAQs'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name_plural': '04. Partners'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '03. Services'},
        ),
        migrations.AlterModelOptions(
            name='shareholder',
            options={'verbose_name_plural': '10. Shareholders'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '02. Slider'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '06. Team Members'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': '07. Testimonials'},
        ),
        migrations.AddField(
            model_name='shareholder',
            name='no_of_share',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='photo',
            field=models.ImageField(default=1, upload_to='shareholder_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shareholder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
