# Generated by Django 3.2 on 2022-12-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0015_auto_20221230_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='name',
        ),
    ]
