# Generated by Django 3.2 on 2022-12-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0016_auto_20221230_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='contact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
