# Generated by Django 3.2 on 2022-12-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0018_auto_20221230_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('invested_amount', models.IntegerField()),
                ('investment_date', models.IntegerField()),
                ('investment_duration', models.IntegerField()),
                ('company_logo', models.ImageField(upload_to='company_profile')),
            ],
            options={
                'verbose_name_plural': '14. Company Profile',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_loan_amount', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('use_of_loan', models.TextField()),
                ('name', models.TextField()),
                ('date_of_birth', models.TextField()),
                ('marital_status', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('how_long', models.TextField()),
                ('present_employer_name', models.TextField()),
                ('occupation', models.TextField()),
                ('years_of_experience', models.TextField()),
                ('gross_monthly_income', models.TextField()),
                ('monthly_rent', models.TextField()),
                ('down_payment', models.TextField()),
                ('comments', models.TextField()),
                ('institution_name', models.TextField()),
                ('saving_account_number', models.TextField()),
                ('address', models.TextField()),
                ('phone_number', models.TextField()),
            ],
            options={
                'verbose_name_plural': '14. Loan Forms',
            },
        ),
        migrations.AddField(
            model_name='companysetup',
            name='company_profile_text',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='shareholder_images/'),
        ),
    ]
