# Generated by Django 3.2 on 2022-12-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0019_auto_20221230_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='investment_date',
            field=models.DateField(),
        ),
    ]
