# Generated by Django 3.2 on 2023-01-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0021_alter_loan_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='how_long',
            new_name='how_long_have_you_lived_in_your_given_address',
        ),
    ]
