# Generated by Django 3.2 on 2023-01-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0023_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
    ]
