# Generated by Django 3.2 on 2023-01-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0026_auto_20230102_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_responded',
            field=models.BooleanField(default=0),
        ),
    ]
