# Generated by Django 3.2 on 2023-01-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0031_loan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
    ]
