# Generated by Django 3.2 on 2023-01-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0033_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='institution_address',
            field=models.TextField(default='dsa'),
            preserve_default=False,
        ),
    ]
