# Generated by Django 3.2 on 2023-01-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0036_alter_loan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='email',
            field=models.CharField(default='sda', max_length=200),
            preserve_default=False,
        ),
    ]
