# Generated by Django 3.2 on 2023-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0037_shareholder_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '18. Sent Mail',
            },
        ),
    ]
