# Generated by Django 3.2 on 2023-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0038_sentmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='verified',
            field=models.BooleanField(default=0),
        ),
    ]
