# Generated by Django 3.2 on 2023-01-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0040_borrower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='verified',
        ),
        migrations.AddField(
            model_name='loan',
            name='is_taxable',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved')], default='pending', max_length=20),
        ),
    ]
