# Generated by Django 3.2 on 2023-01-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0041_auto_20230119_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='is_taxable',
            new_name='loan_status',
        ),
    ]
