# Generated by Django 3.2 on 2023-01-31 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0042_rename_is_taxable_loan_loan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name_plural': '16. Chat'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '13. Contact'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name_plural': '15. Loan Forms'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name_plural': '17. Reply'},
        ),
    ]
