# Generated by Django 3.2 on 2023-01-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0043_auto_20230131_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='down_payment',
        ),
    ]
