# Generated by Django 3.2 on 2023-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0044_remove_loan_down_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='citi_back',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='citi_front',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
